digishare/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#
# from digishare import digishare

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', 'digishare.views.landing', name='landing'),
    url(r'^forum/', include('qa.urls')),
# url(r'^$', 'webtv.views.landing', name='landing'),
]

django_markdown/urls.py
""" Define preview URL. """

from django import VERSION
from django.conf.urls import url

from .views import preview


if VERSION >= (1, 8):
    urlpatterns = [
        url('preview/$', preview, name='django_markdown_preview')
    ]
else:
    # django <= 1.7 compatibility
    from django.conf.urls import patterns
    urlpatterns = patterns(
        '', url('preview/$', preview, name='django_markdown_preview')
    )

qa/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^$', views.QuestionIndexView.as_view(), name='qa_index'),

    url(r'^question/(?P<pk>\d+)/$',
        views.QuestionDetailView.as_view(), name='qa_detail'),

    url(r'^question/(?P<pk>\d+)/(?P<slug>[-_\w]+)/$',
        views.QuestionDetailView.as_view(), name='qa_detail'),

    url(r'^question/answer/(?P<answer_id>\d+)/$',
        views.AnswerQuestionView.as_view(), name='qa_answer_question'),

    url(r'^question/close/(?P<question_id>\d+)/$',
        views.CloseQuestionView.as_view(), name='qa_close_question'),

    url(r'^new-question/$', views.CreateQuestionView.as_view(),
        name='qa_create_question'),

    url(r'^edit-question/(?P<question_id>\d+)/$',
        views.UpdateQuestionView.as_view(),
        name='qa_update_question'),

    url(r'^answer/(?P<question_id>\d+)/$',
        views.CreateAnswerView.as_view(), name='qa_create_answer'),

    url(r'^answer/edit/(?P<answer_id>\d+)/$',
        views.UpdateAnswerView.as_view(), name='qa_update_answer'),

    url(r'^vote/question/(?P<object_id>\d+)/$',
        views.QuestionVoteView.as_view(), name='qa_question_vote'),

    url(r'^vote/answer/(?P<object_id>\d+)/$',
        views.AnswerVoteView.as_view(), name='qa_answer_vote'),

    url(r'^comment-answer/(?P<answer_id>\d+)/$',
        views.CreateAnswerCommentView.as_view(),
        name='qa_create_answer_comment'),

    url(r'^comment-question/(?P<question_id>\d+)/$',
        views.CreateQuestionCommentView.as_view(),
        name='qa_create_question_comment'),

    url(r'^comment-question/edit/(?P<comment_id>\d+)/$',
        views.UpdateQuestionCommentView.as_view(),
        name='qa_update_question_comment'),

    url(r'^comment-answer/edit/(?P<comment_id>\d+)/$',
        views.UpdateAnswerCommentView.as_view(),
        name='qa_update_answer_comment'),

    url(r'^search/$', views.QuestionsSearchView.as_view(), name='qa_search'),

    url(r'^tag/(?P<tag>[-\w]+)/$',
        views.QuestionsByTagView.as_view(), name='qa_tag'),

    url(r'^profile/(?P<user_id>\d+)/$', views.profile, name='qa_profile'),

    url('^markdown/', include('django_markdown.urls')),
]

qa/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django_markdown.models import MarkdownField

from taggit.managers import TaggableManager
from annoying.fields import AutoOneToOneField

class UserQAProfile(models.Model):
    user = AutoOneToOneField(settings.AUTH_USER_MODEL, primary_key=True)
    points = models.IntegerField(default=0)
    # The additional attributes we wish to include.
    website = models.URLField(blank=True)

    def __str__(self):  # pragma: no cover
        return self.user.username


class Question(models.Model):
    slug = models.SlugField(max_length=200)
    title = models.CharField(max_length=200, blank=False)
    description = MarkdownField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    tags = TaggableManager()
    reward = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    closed = models.BooleanField(default=False)
    positive_votes = models.IntegerField(default=0)
    negative_votes = models.IntegerField(default=0)
    total_points = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        self.total_points = self.positive_votes - self.negative_votes
        super(Question, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class Answer(models.Model):
    question = models.ForeignKey(Question)
    answer_text = MarkdownField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    updated = models.DateTimeField('date updated', auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    answer = models.BooleanField(default=False)
    positive_votes = models.IntegerField(default=0)
    negative_votes = models.IntegerField(default=0)
    total_points = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        self.total_points = self.positive_votes - self.negative_votes
        super(Answer, self).save(*args, **kwargs)

    def __str__(self):  # pragma: no cover
        return self.answer_text

    class Meta:
        ordering = ['-answer', '-pub_date']


class VoteParent(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    value = models.BooleanField(default=True)

    class Meta:
        abstract = True


class AnswerVote(VoteParent):
    answer = models.ForeignKey(Answer)

    class Meta:
        unique_together = (('user', 'answer'),)


class QuestionVote(VoteParent):
    question = models.ForeignKey(Question)

    class Meta:
        unique_together = (('user', 'question'),)


class BaseComment(models.Model):
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)

    class Meta:
        abstract = True

    def __str__(self):  # pragma: no cover
        return self.comment_text


class AnswerComment(BaseComment):
    comment_text = MarkdownField()
    answer = models.ForeignKey(Answer)


class QuestionComment(BaseComment):
    comment_text = models.CharField(max_length=250)
    question = models.ForeignKey(Question)

qa/forms.py
from qa.models import UserQAProfile
from django import forms


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserQAProfile
        fields = ('website', 'picture')

qa/views.py
import operator
from functools import reduce
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse
from django.contrib.contenttypes.models import ContentType
from taggit.models import TaggedItem, Tag

from django.db.models import Count
from django.conf import settings
from django.utils.text import slugify
from django.utils.translation import ugettext as _
from django.views.generic import (CreateView, View, ListView, DetailView,
                                  UpdateView)
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db.models import Q
from models import (UserQAProfile, Question, Answer, AnswerVote,
                       QuestionVote, AnswerComment, QuestionComment)
from .mixins import LoginRequired, AuthorRequiredMixin
from .utils import question_score
try:
    qa_messages = 'django.contrib.messages' in settings.INSTALLED_APPS and\
        settings.QA_MESSAGES
except AttributeError:
    qa_messages = False

if qa_messages:
    from django.contrib import messages


"""Dear maintainer:

Once you are done trying to 'optimize' this routine, and have realized what a
terrible mistake that was, please increment the following counter as a warning
to the next guy:

total_hours_wasted_here = 2
"""


class AnswerQuestionView(LoginRequired, View):
    """
    View to select an answer as the satisfying answer to the question,
    validating than the user who created que
    question is the only one allowed to make those changes.
    """
    model = Answer

    def post(self, request, answer_id):
        answer = get_object_or_404(self.model, pk=answer_id)
        if answer.question.user != request.user:
            raise ValidationError(
                "Sorry, you're not allowed to close this question.")
        else:
            # answer.question.closed = True
            # answer.question.save()
            answer.question.answer_set.update(answer=False)
            answer.answer = True
            answer.save()

        next_url = request.POST.get('next', None)
        if next_url is not None:
            return redirect(next_url)

        else:
            return redirect(reverse('qa_index'))


class CloseQuestionView(LoginRequired, View):
    """View to
    mark the question as closed, validating than the user who created que
    question is the only one allowed to make those changes.
    """
    model = Question

    def post(self, request, question_id):
        question = get_object_or_404(self.model, pk=question_id)
        if question.user != request.user:
            raise ValidationError(
                "Sorry, you're not allowed to close this question.")
        else:
            if not question.closed:
                question.closed = True
            else:
                question.closed = False
            question.save()
            # answer.answer = True
            # answer.save()

        next_url = request.POST.get('next', None)
        if next_url is not None:
            return redirect(next_url)

        else:
            return redirect(reverse('qa_index'))


class QuestionIndexView(ListView):
    """CBV to render the index view
    """
    model = Question
    paginate_by = 10
    context_object_name = 'questions'
    template_name = 'qa/index.html'
    ordering = '-pub_date'
	
	

    def get_context_data(self, *args, **kwargs):
        context = super(
            QuestionIndexView, self).get_context_data(*args, **kwargs)
        noans = Question.objects.order_by('-pub_date').filter(
            answer__isnull=True).select_related('user')\
            .annotate(num_answers=Count('answer', distinct=True),
                      num_question_comments=Count('questioncomment',
                      distinct=True))
        context['totalcount'] = Question.objects.count()
        context['anscount'] = Answer.objects.count()
        paginator = Paginator(noans, 10)
        page = self.request.GET.get('noans_page')
        context['active_tab'] = self.request.GET.get('active_tab', 'latest')
        tabs = ['latest', 'unans', 'reward']
        context['active_tab'] = 'latest' if context['active_tab'] not in\
            tabs else context['active_tab']
        try:
            noans = paginator.page(page)
        except PageNotAnInteger:
            noans = paginator.page(1)
        except EmptyPage:
            noans = paginator.page(paginator.num_pages)
        context['totalnoans'] = paginator.count
        context['noans'] = noans
        context['reward'] = Question.objects.order_by('-reward').filter(
            reward__gte=1)[:10]

        question_contenttype = ContentType.objects.get_for_model(Question)
        items = TaggedItem.objects.filter(content_type=question_contenttype)
        context['tags'] = Tag.objects.filter(
            taggit_taggeditem_items__in=items).order_by('-id').distinct()[:10]

        return context

    def get_queryset(self):
        queryset = super(QuestionIndexView, self).get_queryset()\
            .select_related('user')\
            .annotate(num_answers=Count('answer', distinct=True),
                      num_question_comments=Count('questioncomment',
                      distinct=True))
        return queryset


class QuestionsSearchView(QuestionIndexView):
    """
    Display a ListView page inherithed from the QuestionIndexView filtered by
    the search query and sorted by the different elements aggregated.
    """

    def get_queryset(self):
        result = super(QuestionsSearchView, self).get_queryset()
        query = self.request.GET.get('word', '')
        if query:
            query_list = query.split()
            result = result.filter(
                reduce(operator.and_,
                       (Q(title__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(description__icontains=q) for q in query_list))
            )

        return result

    def get_context_data(self, *args, **kwargs):
        context = super(
            QuestionsSearchView, self).get_context_data(*args, **kwargs)
        context['totalcount'] = Question.objects.count
        context['anscount'] = Answer.objects.count
        context['noans'] = Question.objects.order_by('-pub_date').filter(
            answer__isnull=True)[:10]
        context['reward'] = Question.objects.order_by('-reward').filter(
            reward__gte=1)[:10]
        return context


class QuestionsByTagView(ListView):
    """View to call all the questions clasiffied under one specific tag.
    """
    model = Question
    paginate_by = 10
    context_object_name = 'questions'
    template_name = 'qa/index.html'

    def get_queryset(self, **kwargs):
        return Question.objects.filter(tags__slug=self.kwargs['tag'])

    def get_context_data(self, *args, **kwargs):
        context = super(
            QuestionsByTagView, self).get_context_data(*args, **kwargs)
        context['totalcount'] = Question.objects.count
        context['anscount'] = Answer.objects.count
        context['noans'] = Question.objects.order_by('-pub_date').filter(
            tags__name__contains=self.kwargs['tag'], answer__isnull=True)[:10]
        context['reward'] = Question.objects.order_by('-reward').filter(
            tags__name__contains=self.kwargs['tag'],
            reward__gte=1)[:10]
        return context


class CreateQuestionView(LoginRequired, CreateView):
    """
    View to handle the creation of a new question
    """
    template_name = 'qa/create_question.html'
    model = Question
    fields = ['title', 'description', 'tags']
    message = _('Thank you! your question has been created.')

    def form_valid(self, form):
        """
        Create the required relation
        """
        form.instance.user = self.request.user
        return super(CreateQuestionView, self).form_valid(form)

    def get_success_url(self):
        if qa_messages:
            messages.success(
                self.request, self.message)
        return reverse('qa_index')


class UpdateQuestionView(LoginRequired, AuthorRequiredMixin, UpdateView):
    """
    Updates the question
    """
    template_name = 'qa/update_question.html'
    model = Question
    pk_url_kwarg = 'question_id'
    fields = ['title', 'description', 'tags']

    def get_success_url(self):
        question = self.get_object()
        return reverse('qa_detail', kwargs={'pk': question.pk})


class CreateAnswerView(LoginRequired, CreateView):
    """
    View to create new answers for a given question
    """
    template_name = 'qa/create_answer.html'
    model = Answer
    fields = ['answer_text']
    message = _('Thank you! your answer has been posted.')

    def form_valid(self, form):
        """
        Creates the required relationship between answer
        and user/question
        """
        form.instance.user = self.request.user
        form.instance.question_id = self.kwargs['question_id']
        return super(CreateAnswerView, self).form_valid(form)

    def get_success_url(self):
        if qa_messages:
            messages.success(
                self.request, self.message)
        return reverse('qa_detail', kwargs={'pk': self.kwargs['question_id']})


class UpdateAnswerView(LoginRequired, AuthorRequiredMixin, UpdateView):
    """
    Updates the question answer
    """
    template_name = 'qa/update_answer.html'
    model = Answer
    pk_url_kwarg = 'answer_id'
    fields = ['answer_text']

    def get_success_url(self):
        answer = self.get_object()
        return reverse('qa_detail', kwargs={'pk': answer.question.pk})


class CreateAnswerCommentView(LoginRequired, CreateView):
    """
    View to create new comments for a given answer
    """
    template_name = 'qa/create_comment.html'
    model = AnswerComment
    fields = ['comment_text']

qa/templates/qa/create_answer.html
<!--
    Copyright:  Trendzlink Technology Pvt Ltd
    Author:     Deepak MP
-->

{% extends "base.html" %}
{% load django_markdown %}
{% load staticfiles %}
{% block extraconfig2 %}
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/forum_css/forum.css' %}" />
{% endblock %}
{% block topheader %}
    {% include "headerforum.html" %}
{% endblock %}

{% block leftsidebar %}
<div class="col-md-2 col-lg-2 my-div13">
    {% include "menu.html" %}
</div>
{% endblock %}

{% block content %}
<div class="col-md-8 col-xs-12 col-lg-8 col-md-offset-2 col-lg-offset-2" style="padding:0 20px;">
	<div style="height:65px;"><p> &nbsp; </p></div>

  {% if message %}
  <strong>Enter a valid Question!</strong>
  {% endif %}

  <form method="post" action="{% block action_url %}{% url 'qa_create_answer' view.kwargs.question_id %}{% endblock action_url %}">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-success" type="submit" value="Submit Answer"/>
  </form>

</div>

{% endblock content %}

{% block extra_js %}
  {% markdown_editor "#id_answer_text" %}
  {% markdown_media %}
{% endblock %}

qa/templates/qa/detail_question.html
<!--
    Copyright:  Trendzlink Technology Pvt Ltd
    Author:     Deepak MP
-->
{% extends "base.html" %}
{% load django_markdown %}
{% load staticfiles %}
{% block extraconfig2 %}
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/forum_css/forum.css' %}" />
{% endblock %}
{% block topheader %}
    {% include "headerforum.html" %}
{% endblock %}

{% block leftsidebar %}
<div class="col-md-2 col-lg-2 my-div13">
    {% include "menu.html" %}
</div>
<!--
<div class="forum-add-question-block myButton">
    <div class="forum-add-question">
        <a href="">
            <div class="forum-add-question-icon-outer">
                <div class="forum-add-question-icon"><i class="fa fa-plus"></i></div>
            </div>
        </a>
        <div class="forum-add-question-text">Ask New Question</div>
    </div>
</div>-->
{% endblock %}

{% block content %}
<div class="col-md-8 col-xs-12 col-lg-8 col-md-offset-2 col-lg-offset-2" style="padding:0px;">
	<div style="height:65px;"><p> &nbsp; </p></div>
	
	
<div style="padding: 0 20px;">	
{% if question.closed %}
  <div class="closed"></div>
{% else %}
    {% if question.reward %}
    <div class="rewarding"></div>
    {% else %}
    <div class="open"></div>
    {% endif %}
{% endif %}


{% if message %}
    <div class="alert alert-danger" role="alert">{{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endif %}

{% comment %}
{% if question.reward %}
    <div class="alert alert-info" role="alert">This question has been marked to be worth a reward of <b>{{ question.reward }}</b> points!
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
{% endif %}
{% endcomment %}

<div class="panel panel-default box-shadow my-div15 my-div15-first-panel" style="padding:20px;">
  <div class="row">
    <div class="col-sm-12">
      <small class="pull-right">Asked by <span>
		  <a href="{% url 'qa_profile' question.user.id %}">
			  {{ question.user.username }}</a></span>, {{ question.pub_date }}</small>
      {% if user.is_authenticated and question.user == user %}<a href="{% url 'qa_update_question' question.id %}"><small class="pull-right">Edit &nbsp;</small></a>
		{% endif %}
      <h3>{{ question.title }}</h3>
      <h4>{{ question.description|markdown }}</h4>
      <p>
		  <div class="questioncomments" style="display:none;">
{% if last_comments %}
  {% for comment in last_comments %}
  <div class="row">
    <div class="col-md-9 col-md-offset-1">
    <p><b>{{ comment.comment_text|markdown }}</b><small>by <a href="{% url 'qa_profile' comment.user.id %}">{{ comment.user.username }}</a> <div>at {{ comment.pub_date }}</div></small></p>{% if comment.user == user %}<a href="{% url 'qa_update_question_comment' comment.id %}" class="pull-left"><small><u>Edit</u>&nbsp;</small></a>{% endif %}
    </div>
  </div>
  {% endfor %}
			{% else %}<h5>No comments</h5>{% endif %}</div>
      {% if question.closed %}
          <p class="pull-right">This Question has been closed.</p>
      {% else %}
		  <a class="viewcomments" role="button"><u><span>View Comments</span></u></a>
          <a class="" href="{% url 'qa_create_question_comment' question.id %}" role="button"><u>Add Comment</u></a>
      {% endif %}
        {% if user.is_authenticated and question.user != user %}
      <div class ="col-sm-3"><div class="row">
        <form action="{% url 'qa_question_vote' question.id %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ request.path }}">
          <input type="hidden" name="upvote" value="on">
          <button type="submit" class="btn btn-sm btn-success pull-left" data-toggle="tooltip" data-placement="top" title="Vote Up this answer"><span>Upvote | {{ question.total_points }}</span></button>
        </form>
          <form action="{% url 'qa_question_vote' question.id %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ request.path }}">
          <button style="margin-left:10px;" type="submit" class="btn btn-sm pull-left" data-toggle="tooltip" data-placement="bottom" title="Vote Down this answer"><span>Downvote</span></button>
        </form>
      </div></div>
    {% endif %}
    </div>
  </div>
</div>

		<script>
        $(".viewcomments").click(function() {
          $('.questioncomments').slideToggle().toggleClass('active');
			if ($('.questioncomments').hasClass('active')) {
            $('.viewcomments span').text('Hide Comments');
          } else {
            $('.viewcomments span').text('View Comments');
          }
        });
        </script>

  <h3>Answers</h3>

{% if answers %}
			    
    {% for answer in answers %}


<div class="col-sm-12 panel panel-default box-shadow my-div15 my-div15-first-panel" style="padding-bottom:20px;padding-left:0px;">
    {% if user.is_authenticated and answer.user != user %}
      <div class ="col-md-1 col-sm-1" style="display:block;padding:2px;padding-top:20px;width:auto;">
          <form action="{% url 'qa_answer_vote' answer.id %}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ request.path }}">
              <input type="hidden" name="upvote" value="on">
              <button type="submit" class="btn btn-sm btn-success" data-toggle="tooltip" data-placement="top" title="Vote Up this answer"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button>
          </form>
              <big class="custom-big"><b>&nbsp;&nbsp;&nbsp;{{ answer.total_points }}</b></big><br>
          <form action="{% url 'qa_answer_vote' answer.id %}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ request.path }}">
              <button type="submit" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="bottom" title="Vote Down this answer"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span></button>
          </form>
      </div>
    {% endif %}
						
      <div class ="col-md-10" style="padding-left:0px;">
          <div id="ans" class="alert alert-primary" role="alert">{{ answer.answer_text|markdown }}</div>
		  
		  <div class="answercomments{{ answer.pk }} col-md-11 col-md-offset-1 pull-right" style="display:none;">
        {% if answer.answercomment_set %}
          {% for comment in answer.answercomment_set.all %}
			  <div style="border-bottom:solid;border-width:1px;border-color:gray;"><div class="row">
				  <div class="col-md-8">
					  <p><b>{{ comment.comment_text|markdown }}</b></p></div>
				<div class="col-md-4"><p><small>
					<div class="pull-right">at {{ comment.pub_date }}</div>
					<a href="{% url 'qa_profile' comment.user.id %}" class="pull-right">by {{ comment.user.username }}&nbsp;</a>
				</small>
					</p><div style="clear:both;"></div>
			  {% if comment.user == user %}<a href="{% url 'qa_update_answer_comment' comment.id %}" class="pull-right"><small>&nbsp;&nbsp;&nbsp;<u>Edit</u>&nbsp;</small></a>{% endif %}
			  </div></div></div>
          {% endfor %}
        {% endif %}{% if answer.answercomment_set.all|length == 0 %}<p>No comments</p>{% endif %}
	  <br><a href="{% url 'qa_create_answer_comment' answer.id %}">
			<small><u>Add comment</u>&nbsp;<span class="glyphicon glyphicon-comment" aria-hidden="true"></span></small></a><hr>
      </div>
		  
        
		  
          <div class ="col-md-5">
            <p class="">Answer by<b>
				<a href="{% url 'qa_profile' answer.user.id %}">{{ answer.user.username }}&nbsp;</a>({{ answer.user.userqaprofile.points }})</b>
			  </p>
			  {% if answer.user == user %}<a href="{% url 'qa_update_answer' answer.id %}"><small><u>Edit Answer</u>&nbsp;</small></a>{% endif %}
			  <a class="viewanswercomments{{ answer.pk }}"><small><u><span>Show comments ({{ answer.answercomment_set.all|length }})</span></u></small></a>

          </div>
    </div>
                {% if user.is_authenticated and answer.question.user == user and answer.question.closed == False and answer.user != user %}
                    <form action="{% url 'qa_close_question' question.id %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}"/>
                        <button type="submit" class="btn btn-success btn-sm pull-right" data-toggle="tooltip" data-placement="bottom" title="Close this question"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></button>
                    </form>
                {% else %}
                    {% if  answer.answer == True %}
                        <button class="btn btn-success btn-sm pull-right" title="Picked Answer"><span class="glyphicon glyphicon-star" aria-hidden="true"></span></button>
                    {% endif %}
                {% endif %}
</div>

			<script>
        $(".viewanswercomments{{ answer.pk }}").click(function() {
          $('.answercomments{{ answer.pk }}').slideToggle().toggleClass('active');
			if ($('.answercomments{{ answer.pk }}').hasClass('active')) {
            $('.viewanswercomments{{ answer.pk }} span').text('Hide comments');
          } else {
            $('.viewanswercomments{{ answer.pk }} span').text('Show comments ({{ answer.answercomment_set.all|length }})');
          }
        });
        </script>
    {% endfor %}
</div>
{% else %}
<div class="panel panel-default box-shadow my-div15 my-div15-first-panel" style="padding:20px;">
<center><h2>This question is still open, <a href="{% url 'qa_create_answer' question.id %}" role="button"><u>write answer!</u></a></h2></center>
</div>
    {% endif %}
		</div>
<div>
	{% block newanswer %}
<div class="forum-add-question-block1 myButton">
    <div class="forum-add-question">
        <a href="{% url 'qa_create_answer' question.id %}">
                <div class="forum-add-question-icon-outer">
                    <div class="forum-add-question-icon"><i class="fa fa-plus"></i></div>
                </div>
        </a>
    </div>
</div>
	{% endblock newanswer %}
{% endblock content %}
{% block extra_js %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>
{% endblock extra_js %}
</div>

qa/templates/qa/update_answer.html
<!--
    Copyright:  Trendzlink Technology Pvt Ltd
    Author:     Deepak MP
-->
{% extends 'qa/create_answer.html' %}

{% block action_url %}
{% url 'qa_update_answer' view.kwargs.answer_id %}
{% endblock action_url %}

qa/templates/qa/update_question.html
<!--
    Copyright:  Trendzlink Technology Pvt Ltd
    Author:     Deepak MP
-->
{% extends 'qa/create_question.html' %}

{% block action_url %}
{% url 'qa_update_question' view.kwargs.question_id %}
{% endblock action_url %}